Repository release-kit/semver, pull requests merged in 2023-05, with the labels that each got.

#25 run on node16
  action.yml
Labels: feature

#26 Fix typo
  README.md
Labels: documentation

#27 Update to v2
  .eslintrc.js
  .prettierrc
  README.md
  action.yml
  dist/index.js
  package.json
  src/__snapshots__/options.test.ts.snap
  src/env.d.ts
  src/extract.ts
  src/index.ts
  src/options.test.ts
  src/options.ts
  src/parse.ts
  yarn.lock
Labels: feature

#28 Update release workflow
  .github/workflows/release.yml
Labels: chore

#29 Update release workflow 2
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: chore

#30 Update release workflow 3
  dist/index.js
  package.json
  rollup.config.mjs
  src/index.ts
  yarn.lock
Labels: chore

#31 Update release workflow 4
  dist/index.js
  rollup.config.js
  rollup.config.mjs
Labels: chore

#32 Update release workflow 5
  .github/workflows/release.yml
Labels: chore

#33 Refactor release workflow
  .github/workflows/release.yml
Labels: chore
